# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/nbs/05_interp.ipynb (unless otherwise specified).

__all__ = []

# Cell
from fastai.basics import *

# Cell
@patch
@delegates(TfmdDL.show_results)
def show_at(self:Interpretation, idxs, **kwargs):
    "Show predictions on the items at `idxs`"
    inp, _, targ, dec, _ = self[idxs]
    self.dl.show_results((inp, dec), targ, **kwargs)