# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_basics.interp.show_at.ipynb (unless otherwise specified).

__all__ = []

# Cell
@patch
def __getitem__(self:Interpretation, idxs):
    "Get the inputs, preds, targets, decoded outputs, and losses at `idx`"
    if not is_listy(idxs): idxs = [idxs]
    attrs = 'inputs,preds,targs,decoded,losses'
    res = L([getattr(self, attr)[idxs] for attr in attrs.split(',')])
    return res

@patch
def show_at(self:Interpretation, idx:int, **kwargs):
    inp, _, targ, dec, _ = self[idx]
    dec, targ = L(dec, targ).map(Self.unsqueeze(0))
    self.dl.show_results((inp, dec), targ, **kwargs)