# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_learner": "05_Inference_Server.ipynb",
         "make_datasets": "05_Inference_Server.ipynb",
         "save_im": "05_Inference_Server.ipynb",
         "inference": "05_Inference_Server.ipynb",
         "get_feats": "05_Style_Transfer.ipynb",
         "url": "05_Style_Transfer.ipynb",
         "get_style_im": "05_Style_Transfer.ipynb",
         "gram": "05_Style_Transfer.ipynb",
         "get_stl_fs": "05_Style_Transfer.ipynb",
         "style_loss": "05_Style_Transfer.ipynb",
         "FeatureLoss": "05_Style_Transfer.ipynb",
         "act_loss": "05_Style_Transfer.ipynb",
         "ReflectionLayer": "05_Style_Transfer.ipynb",
         "ResidualBlock": "05_Style_Transfer.ipynb",
         "UpsampleConvLayer": "05_Style_Transfer.ipynb",
         "TransformerNet": "05_Style_Transfer.ipynb"}

modules = ["deployment.py",
           "style_transfer.py"]

doc_url = "https://walkwithfastai.com/"

git_url = "https://github.com/walkwithfastai/walkwithfastai.github.io/tree/master/"

def custom_doc_links(name):
    from nbdev.showdoc import try_external_doc_link
    return try_external_doc_link(name, ['fastcore', 'nbdev', 'fastai', 'timm'])
